gui:
    sidePanelWidth: 0.25
    expandFocusedSidePanel: true
    nerdFontsVersion: "3"
    authorColors:
        "Ahmed Kamal": "magenta"
    showRandomTip: false
    showCommandLog: false
git:
    parseEmoji: true
    commit:
        autoWrapCommitMessage: true
        autoWrapWidth: 72
    paging:
        colorArg: always
        pager: delta --dark --paging=never
os:
    copyToClipboardCmd: "pbcopy < {{text}}"
    editPreset: "vscode"
    open: "open {{filename}}"
