tap "bufbuild/buf", trusted: {
  formula:  "buf",
}

tap "dotenvx/brew", trusted: {
  formula:  "dotenvx",
}

tap "koekeishiya/formulae", trusted: {
  formula:  "skhd",
}

# Dev Tools
brew "buf"
brew "dotenvx"
brew "git"
brew "git-delta"
brew "go"
brew "gpg"                                  # 🛡️ The GNU Privacy Guard, used for encryption and signing of messages or data.
brew "graphviz"
brew "grpcui"
brew "grpcurl"
brew "neovim"
brew "npm"
brew "protoc-gen-go-grpc"
brew "rustup"
brew "tokei"                                # 📉 Displays statistics about your code.
brew "tree-sitter-cli"

# Docker 🐳
brew "ctop"
brew "dive"
brew "lazydocker"

# K8s
brew "argocd"
brew "cilium-cli"
brew "helm"
brew "helm-docs"
brew "k9s"
brew "kind"
brew "kubectx"                              # 🕸️ Switches between kubectl contexts easily and creates aliases.

# General tools
brew "koekeishiya/formulae/skhd"            # 🥵 A simple hotkey daemon.
brew "mosh"                                 # 🕹️ Remote terminal application that allows roaming.

# Terminal Tools
brew "age"                                  # 👴 A modern and secure file encryption tool.
brew "atuin"                                # 📜 Replaces your existing shell history with a SQLite database.
brew "bash"                                 # 🐣 Bourne again shell.
brew "bash-completion"                      # Auto completions for `bash`.
brew "bat"                                  # 🦇 A cat(1) clone with wings.
brew "bottom"                               # 🖥️ A monitor of resources. Rust version.
brew "brew-cask-completion"
brew "broot"                                # 🌴 A new way to see and navigate directory trees.
brew "btop"                                 # 📊 Resources monitor. C++ version and continuation of bashtop and bpytop.
brew "carapace"                             # A multi-shell completion library and binary.
brew "coreutils"                            # ☢️ A list of commands from the GNU Core Utilities https://en.wikipedia.org/wiki/List_of_GNU_Core_Utilities_commands#File_Utilities.
brew "direnv"                               # 🗂️ Loads and unloads environment variables depending on the current directory.
brew "diffr"                                # ➖ Reviewing changes involves reading diffs.
brew "duf"                                  # 💾 Disk Usage/Free Utility - a better 'df' alternative.
brew "dust"                                 # 💿 A more intuitive version of du in rust.
brew "eza"                                  # 📋 A modern alternative to ls.
brew "fd"                                   # 🔎 A simple, fast and user-friendly alternative to 'find'.
brew "fzf"                                  # 🌸 A command-line fuzzy finder
brew "glow"                                 # ✨ Render markdown on the CLI.
brew "hyperfine"                            # 🏇 A command-line benchmarking tool, written in Rust.
brew "jj"                                   # A powerful version control system.
brew "jq"
brew "keychain"                             # 🔐 A user-friendly front-end to ssh-agent.
brew "lazygit"                              # 💤 A simple terminal UI for git commands.
brew "mas"                                  # 📦 A Mac App Store command line interface.
brew "mkcert"                               # 🎓 A simple zero-config tool to make locally trusted development certificates with any names you'd like.
brew "nushell"                              # 🐚 A new type of shell.
brew "nmap"                                 # 🕵️‍♂️ A port scanning utility for large networks.
brew "pinentry-mac"                         # ⌨  Pinentry for GPG on Mac.
brew "portal"                               # 💻 Sends files from any computer to another.
brew "procs"                                # Lists all processes.
brew "ripgrep"                              # 🧐 Recursive Regex search tool.
brew "safe-rm"                              # ❌ Prevent the accidental deletion of important files.
brew "sd"                                   # Intuitive find & replace CLI (sed alternative).
brew "specify"                              # 💫 A toolkit to help you get started with Spec-Driven Development.
brew "sponge"                               # 🧽 A tool similar to tee, but soaks up all its input before opening the output file.
brew "starship"                             # 🚀 Starship cross-shell prompt.
brew "stow"                                 # 🔗 A symlink farm manager.
brew "teleport"                             # 🚪 A modern SSH server for teams managing distributed infrastructure.
brew "telnet"
brew "termshark"                            # 🦈 Provides a terminal-based user interface for analyzing packet captures.
brew "cf-terraforming"
brew "tldr"                                 # 📰 A simplified and community-driven man pages.
brew "tmux"                                 # 🫖 mux.
brew "tpm"                                  # 🧋 A plugin manager for tmux.
brew "trash-cli"                            # 🗑️ A command line interface to the trashcan.
brew "tree"                                 # 🌳
brew "trivy"                                # 🕵🏻‍♂️ A security scanner for vulnerabilities, misconfigurations, secrets.
brew "unp"                                  # 📦 Unpack any archive.
brew "vivid"                                # 🎨 A themeable LS_COLORS generator with a rich filetype database.
brew "watch"                                # ⌚︎  Executes a program periodically, showing output fullscreen.
brew "wget"
brew "xh"                                   # 🎮 A friendly and fast tool for sending HTTP requests, written in Rust.
brew "yazi"                                 # 💥 A blazing fast terminal file manager written in Rust, based on async I/O.
brew "yq"
brew "zoxide"                               # 🤓 A smarter cd command.

# Terminal Fun
brew "cowsay"
brew "fortune"
brew "lolcat"
brew "fastfetch"

# Apps
cask "caffeine"                             # ☕️ Prevents the system from going to sleep.
cask "chatgpt"                              # 🤖 💬GPT.
cask "claude"                               # 🤖 Claude.
cask "claude-code"                          # 🤖 Claude code.
cask "codex"                                # 🤖 Open AI codex.
cask "coderabbit"                           # 🐰
cask "handy"                                # ✋ A speech-to-text application.
cask "jetbrains-toolbox"
cask "orbstack"                             # ⚡️ Fast, light, and simple way to run containers and Linux machines.
cask "postman"
cask "raycast"
cask "rectangle"
cask "slack"
cask "zed"

# Terminals
cask "ghostty"                              # 👻 An ultra fast terminal emulator.

# Fonts - Nerd fonts for the terminal - https://www.nerdfonts.com/
cask "font-comic-shanns-mono-nerd-font"     # ComicShannsMono Nerd Font
cask "font-envy-code-r-nerd-font"           # EnvyCodeR Nerd Font
cask "font-hack-nerd-font"                  # Hack Nerd Font
cask "font-jetbrains-mono-nerd-font"        # JetbrainsMono Nerd Font
cask "font-sauce-code-pro-nerd-font"        # Source Code Pro Mono Nerd Font

# Fonts - Normal
cask "font-open-sans"
cask "font-roboto"
cask "font-source-code-pro"

# Web Browsers
cask "arc"
cask "brave-browser"
cask "firefox"

# Mac Apps
mas "RunCat Neo", id: 6757801838
