tap "bufbuild/buf"
tap "dotenvx/brew"
tap "FelixKratz/formulae"
tap "homebrew/bundle"
tap "julien-cpsn/atac"
tap "koekeishiya/formulae"
tap "owasp-amass/amass"

# Dev Tools
brew "bufbuild/buf/buf"
brew "dotenvx/brew/dotenvx"
brew "git"
brew "git-delta"
brew "go"
brew "gpg"                                  # 🛡️ The GNU Privacy Guard, used for encryption and signing of messages or data.
brew "graphviz"
brew "grpcui"
brew "grpcurl"
brew "neovim"
brew "protoc-gen-go"
brew "protoc-gen-go-grpc"
brew "tokei"                                # 📉 Displays statistics about your code.
brew "zig"

# Docker 🐳
brew "ctop"
brew "dive"
brew "lazydocker"

# K8s
brew "argocd"
brew "helm"
brew "k9s"
brew "kind"
brew "kubectx"                              # 🕸️ Switches between kubectl contexts easily and creates aliases.

# General tools
brew "koekeishiya/formulae/skhd"            # 🥵 A simple hotkey daemon.
brew "koekeishiya/formulae/yabai"           # 🪟A tiling window manager for macOS based on binary space partitioning.
brew "mosh"                                 # 🕹️ Remote terminal application that allows roaming.

# Security
brew "amass"                                # 🛜 Performs network mapping of attack surfaces and external asset discovery.
brew "nikto"                                # 🌐 Web server scanner.

# Terminal Tools
brew "age"                                  # 👴 A modern and secure file encryption tool.
brew "atac"                                 # ✉️ Arguably a Terminal API Client (like postman).
brew "atuin"                                # 📜 Replaces your existing shell history with a SQLite database.
brew "bash"                                 # 🐣 Bourne again shell.
brew "bash-completion"                      # Auto completions for `bash`.
brew "bat"                                  # 🦇 A cat(1) clone with wings.
brew "bottom"                               # 🖥️ A monitor of resources. Rust version.
brew "brew-cask-completion"
brew "broot"                                # 🌴 A new way to see and navigate directory trees.
brew "btop"                                 # 📊 Resources monitor. C++ version and continuation of bashtop and bpytop.
brew "coreutils"                            # ☢️ A list of commands from the GNU Core Utilities https://en.wikipedia.org/wiki/List_of_GNU_Core_Utilities_commands#File_Utilities.
brew "direnv"                               # 🗂️ Loads and unloads environment variables depending on the current directory.
brew "diffr"                                # ➖ Reviewing changes involves reading diffs.
# brew "dog"                                # Not maintained upstream.
brew "duf"                                  # 💾 Disk Usage/Free Utility - a better 'df' alternative.
brew "dust"                                 # 💿 A more intuitive version of du in rust.
brew "eza"                                  # 📋 A modern alternative to ls.
brew "fd"                                   # 🔎 A simple, fast and user-friendly alternative to 'find'.
brew "sketchybar"                           # ✨ Creates a highly flexible, customizable, and fast status bar replacement.
brew "fzf"                                  # 🌸 A command-line fuzzy finder
brew "glow"                                 # ✨ Render markdown on the CLI.
brew "hyperfine"                            # 🏇 A command-line benchmarking tool, written in Rust.
brew "jq"
brew "keychain"                             # 🔐 A user-friendly front-end to ssh-agent.
brew "lazygit"                              # 💤 A simple terminal UI for git commands.
brew "mas"                                  # 📦 A Mac App Store command line interface.
brew "midnight-commander"                   # 🌃 A visual file manager.
brew "mkcert"                               # 🎓 A simple zero-config tool to make locally trusted development certificates with any names you'd like.
brew "nushell"                              # 🐚 A new type of shell.
brew "nmap"                                 # 🕵️‍♂️ A port scanning utility for large networks.
brew "pinentry-mac"                         # ⌨ Pinentry for GPG on Mac.
brew "portal"                               # 💻 Sends files from any computer to another.
brew "ripgrep"                              # 🧐 Recursive Regex search tool.
brew "safe-rm"                              # ❌ Prevent the accidental deletion of important files.
brew "sd"                                   # Intuitive find & replace CLI (sed alternative).
brew "sponge"                               # 🧽 A tool similar to tee, but soaks up all its input before opening the output file.
brew "starship"                             # 🚀 Starship cross-shell prompt.
brew "stow"                                 # 🔗 A symlink farm manager.
brew "teleport"                             # 🚪 A modern SSH server for teams managing distributed infrastructure.
brew "telnet"
brew "termshark"                            # 🦈 Provides a terminal-based user interface for analyzing packet captures.
brew "terraform"
brew "tldr"                                 # 📰 A simplified and community-driven man pages.
brew "tmux"                                 # 🫖 mux.
brew "tpm"                                  # 🧋 A plugin manager for tmux.
brew "trash-cli"                            # 🗑️ A command line interface to the trashcan.
brew "tree"                                 # 🌳
brew "vivid"                                # 🎨 A themeable LS_COLORS generator with a rich filetype database.
brew "watch"                                # ⌚︎ Executes a program periodically, showing output fullscreen.
brew "wget"
brew "xh"                                   # 🎮 A friendly and fast tool for sending HTTP requests, written in Rust.
brew "yazi"                                 # 💥 A blazing fast terminal file manager written in Rust, based on async I/O.
brew "yq"
brew "zoxide"                               # 🤓 A smarter cd command.

# Terminal Fun
brew "asciiquarium"
brew "cmatrix"
brew "cowsay"
brew "fortune"
brew "lolcat"
brew "neofetch"

# Zsh
brew "zsh-autocomplete"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-fast-syntax-highlighting"
brew "zsh-history-substring-search"

# Apps
cask "caffeine"                             # ☕️ Prevents the system from going to sleep.
cask "chatgpt"
cask "dropbox"
cask "deepl"                                # 🤖Translator.
cask "jetbrains-toolbox"
cask "mitmproxy"                            # Intercepts, modifies, replays, saves HTTP/S traffic.
cask "nikitabobko/tap/aerospace"            # i3-like tiling window manager for macOS.
cask "nordvpn"
cask "obsidian"
cask "orbstack"                             # ⚡️ Fast, light, and simple way to run containers and Linux machines.
cask "podman-desktop"
cask "postman"
# cask "raycast"
cask "rectangle"
cask "signal"
cask "slack"
cask "telegram"
cask "visual-studio-code"
cask "zed"

# Terminals
cask "ghostty"                              # 👻An ultra fast terminal emulator.
cask "warp"                                 # 🎁 An AI friendly terminal emulator.
cask "wezterm"                              # 🧙‍♂️A wizzard terminal emulator.

# Fonts - Nerd fonts for the terminal - https://www.nerdfonts.com/
cask "font-comic-shanns-mono-nerd-font"     # ComicShannsMono Nerd Font
cask "font-envy-code-r-nerd-font"           # EnvyCodeR Nerd Font
cask "font-hack-nerd-font"                  # Hack Nerd Font
cask "font-jetbrains-mono-nerd-font"        # JetbrainsMono Nerd Font
cask "font-sauce-code-pro-nerd-font"        # Source Code Pro Mono Nerd Font

# Fonts - Normal
cask "font-open-sans"
cask "font-roboto"
cask "font-source-code-pro"

# Web Browsers
cask "arc"
cask "brave-browser"
cask "firefox"

# Mac Apps
mas "RunCat", id: 1429033973

# Visual Studio Code Plugins
vscode "1YiB.rust-bundle"
vscode "Catppuccin.catppuccin-vsc"
vscode "Catppuccin.catppuccin-vsc-icons"
vscode "dooez.alt-catppuccin-vsc"
vscode "golang.Go"
vscode "hashicorp.terraform"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-vscode.makefile-tools"
vscode "mvllow.rose-pine"
vscode "MattFoulks.har-analyzer"
